### ISSUE TITLE
Support enabling/disabling ruff linting from the configuration

### ISSUE THREAD

**Issue by noirbizarre** [astral-sh/ruff-vscode#115]
Hi 👋🏼 

I know it is possible to disable the `vscode-ruff` plugin to disable `ruff` linting.
While it is sustainable if you work on a few projects and not often switching between ruff-enabled or not, it is becoming a nightmare to manage as soon as you have many and switching often between enabled/disabled.
The main issue is that it is not possible to activate/deactivate a plugin from the `settings.json` or the `*.code-workspace` and in the case of multiroots workspaces, it is not possible to have `ruff` enabled on one directory and not another.

So, is it possible to have a `ruff.enabled: true/false` setting allowing to easily toggle `ruff` by workspace/project/directory ? 

Note: This would also allow external tools to dynamically set it from the conf because they can't access VSCode internal plugins states, and I am precisely working on one of those tools.

Naïve question: why is it not possible to have `ruff` listed in the `VSCode Python` settings choices as linter, sorter... ? Is it an upstream (VSCode or vscode-python) limitation with the extension kit ? Having homogenous settings for all Python would be great (ie. `python.linting.ruffEnabled`, `python.linting.ruffPath`, `python.linting.ruffArgs`, the ability to toggle all linters once with `python.linting.enabled` as well as reusing VSCode Python current interpreter).

**Comment by charliermarsh** [comment]
Hey! I think we could support this. Can you think of any extensions with a similar setting?

With regards to the default `VSCode Python` settings: it was a while ago, but IIRC, we did try to do this, but were told by the Microsoft team (https://github.com/microsoft/vscode-python/issues/19843) that they want plugins to implement their own extensions rather than bundling more tools into the `VSCode Python`.

**Comment by noirbizarre** [comment]
Interesting discussion, which seems to be good news: 

> The python extension itself is migrating to the model where the tools, based on the usage that we see, will have their own extension. So far, we have created, pylint, flake8, black and isort extensions. Unfortunately, we won't be able to take on ruff linter.

If I understand well, they are taking the opposite position: only keeping the core in `vscode-python` and considering all tools as extensions too.

> Can you think of any extensions with a similar setting?

I took the `vscode-python` linters patterns, but I just did a search on `enabled` in the VSCode parameters screen, and it seems to be more standard than I expected (even if most of the time this is only to toggle individual features). Just a few examples, having a global toggle:
- `Prettier` > `prettier.enable`
- `Git` > `git.enabled`
- `Markdown Math` > `markdown.math.enabled`

**Comment by Andrei-Aksionov** [comment]
@noirbizarre Ruff accepts cli arguments, so as a warkaround you can provide something like:
```json
"ruff.args": ["--select=[]"]
```
At least it works for me.

@charliermarsh Just want to confirm that it happens sometimes that I need to disable all my linters, auto-formatters, auto correction trailing whitespaces and other stuff, when I need to work on a project that was maintained not by me, but the team expects my inputs. Otherwise the whole project will be glowing like a christmas tree because of all the linting warnings.

**Comment by charliermarsh** [comment]
(This is still something I'd like to support, PR welcome of course.)

**Comment by Andrei-Aksionov** [comment]
@charliermarsh I would also want you to support this, because my "solution" is an ad-hoc one 😺 .
But my specialization is in ML, so that means pytorch and python mostly.
I took a look at this repo and I've noticed that there are some parts of code in python, but it related to build and test, so I don't think that I will be able to disable it through tests, but who knows 🤷 . From your profile I see that you was a staff software engineer, so I bet you saw a lot of weird staff (non pun intended) in your career.

I also noticed that this repo has `pyproject.toml` file, but you use pip-compile, not poetry. Maybe you have something against it. If not I can work on it.
Though I haven't worked with pip-compile, maybe it has some benefits that I don't see. For me it just looks weird to have two requirements (dev and non-dev) with hash values and overlapping packages, when you can achieve this with groups in `pyproject.toml`, while `poetry.lock` will store all the hashes.
You can see an example in my [repo](https://github.com/Andrei-Aksionov/nanoGPTplus/blob/main/pyproject.toml).

**Comment by parched** [comment]
Could we also disable the flake8 extension when this is enabled? https://github.com/microsoft/vscode-flake8/issues/146

**Comment by kevalmorabia97** [comment]
This would be very helpful feature. I work on multiple repositories and only one of them have ruff configurations in pyproject.toml but vscode uses ruff by default for fixing all repositories. What's worse is that ruff ends up using default configuration for other repositories since they only have flake8 / isort toml configurations and not ruff configurations.

I think by default ruff should be disabled in vscode and only when you explicitly enable in settings.json should it be used
