### ISSUE TITLE
Auto restart ruff server when config changes

### ISSUE THREAD

**Issue by jd-solanki** [astral-sh/ruff-vscode#281]
Hi 👋🏻 

Thanks for the ruff. It's super incredible. I wanted a Python tool similar to ESLint and ruff is doing a perfect job. ❤️ 

I started using ruff and I noticed when I update the rules (In this example, I'm turning off the rule) in `ruff.toml`, the linting server isn't restarted automatically causing the warning to persist and I have to manually restart the server to ensure I have disabled the rule & get rid of warning lines in my code.

> P.S. I'm using `ruff.toml` and we should do the same for other config files where ruff rules can be written like `pyproject.toml`

**Comment by dhruvmanila** [comment]
Yes, this feature is available in the native server: https://docs.astral.sh/ruff/editors/features/#dynamic-configuration although I think it requires some additional configuration in Neovim because the client doesn't provide any handle for `workspace/diagnostics/refresh`. I'll open an issue in Neovim for this.

**Comment by MichaReiser** [comment]
I think we can close this as it is implemented in the native server and this is about the vs code extension (doesn't apply to neovim)
