### ISSUE TITLE
 Issue with remote SSH not working?

### ISSUE THREAD

**Issue by FlatMapIO** [astral-sh/ruff-vscode#324]
I have tested it on macOS locally and it works fine, but when I try to format remotely using SSH, VSCode pops up "There is no formatter for 'python' files installed." and I have installed Ruff and VSCode extension in the remote environment correctly.

remote SSH (linux)
--------------------------
which ruff => /opt/homebrew/bin/ruff

extension: Ruff v2023.44.0

vscode settings: 
```json
  "[python]": {
    "editor.defaultFormatter": "charliermarsh.ruff"
  },
```

**Comment by MichaReiser** [comment]
Can you tell us a bit about your SSH setup?  I never SSH into another machine (other than from the terminal)

**Comment by dhruvmanila** [comment]
I'm not 100% sure but maybe it's because the extension is registered to only work with on-disk documents:

https://github.com/astral-sh/ruff-vscode/blob/9b1f9cda6bec1847000312e026db6ecc6def111f/src/common/server.ts#L61-L69

Here, we might have to add another entry: `{ scheme: "ssh", language: "python" }`?

* https://code.visualstudio.com/api/references/vscode-api#DocumentFilter
* https://code.visualstudio.com/api/references/vscode-api#Uri.scheme

**Comment by yaroslavsadin** [comment]
I guess I hit this as well, using Ruff together with Remote SSH vscode plugin. No highlighting in python files that way

**Comment by FlatMapIO** [comment]
I retried the ruff extension today, and it works fine, (I'm using vscode-insider which is upgrading all the time), and I'm now closing the issue

**Comment by charliermarsh** [comment]
Thanks for following up @FlatMapIO.

**Comment by nikhilweee** [comment]
For me the fix was to check if I was using the correct python interpreter. Open Command Pallete (`Ctrl + Shift + P`) > `Python: Select Interpreter` and select the one which has `ruff` installed.
