### ISSUE TITLE
Unable to install on VSCode 1.87.2 on Windows 11 Pro

### ISSUE THREAD

**Issue by dvadovsz-netapp** [astral-sh/ruff-vscode#430]
Ruff version 2024.16.0
VSCode version 1.87.2
OS: Windows 11 Pro

When clicking the install button from the extension explorer, it says that it is incompatible with 1.87.2

![image](https://github.com/astral-sh/ruff-vscode/assets/135053091/16a99972-5b1f-496f-8344-9314d3346cba)

Strangely, the same version of VSCode on Linux (Gentoo) installs successfully on my home machine, but I don't see any error highlighting. I need to run 'ruff check' manually. (I'm a new user, so I'm not exactly sure what should work here.)

**Comment by zanieb** [comment]
Hm that's very weird. It should "just work", I've never seen anything like this.

I'm on v1.87.2 as well.

**Comment by MichaReiser** [comment]
That's strange indeed. I just booted into my Windows, updated VS code and installed the Ruff extension and it worked without any problems. 

Would you mind sharing the text from VSCode - Help - About? It should look like this:

```
Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
```
I'm asking because I wonder if there's some other compatibility issue and VS code shows some random error message instead.
