### ISSUE TITLE
Organize imports does not respect a line-length override

### ISSUE THREAD

**Issue by strattao** [astral-sh/ruff-vscode#435]
I have this override in my vscode.settings file:
{
    "ruff.format.args": ["--config", "line-length=99"],
}

The line length override appears to be respected except when sorting the imports. What am I missing?

**Comment by MichaReiser** [comment]
Hy @strattao 

import sorting is implemented as a lint rule today. That's why you have to also set `ruff.lint.args": ["--config", "line-length=99"]`. I agree, having to specify the line length twice is a bit awkward. CC: @snowsignal who's designing our new LSP and is thinking about what settings to expose

**Comment by strattao** [comment]
Got it, that works. Thanks and sorry for the hassle!
