### ISSUE TITLE
Handle invalid configuration more gracefully

### ISSUE THREAD

**Issue by jvacek** [astral-sh/ruff-vscode#635]
If enforcing the ruff version in pyproject.toml via [`required-version`](https://docs.astral.sh/ruff/settings/#required-version), the VSCode plugin errors out like this:

<img width="502" alt="image" src="https://github.com/user-attachments/assets/d1a8e265-9549-400b-b14d-e8b7ff4e0813">

It would be nicer if this was handled a bit more explicitly instead of just "refer to the logs"

**Comment by dhruvmanila** [comment]
The issue here is that there could be multiple errors that the server discovers while indexing the project and the way it currently works is that it adds these errors in the Ruff output channel and displays a notification (like the one in the issue description) to check the logs. Otherwise, there's a chance that it notification popup is filled with multiple lines of text

**Comment by jvacek** [comment]
Is there a way to maybe raise instead a warning that says something like `Ruff server failed to start, please check the logs in Output → Ruff` or something like this instead so it's a bit more "evident" it's a ruff issue?

**Comment by dhruvmanila** [comment]
@jvacek I'm not sure what you mean. The notification does include the source of the notification which is "Ruff".

**Comment by jvacek** [comment]
Hmm yeah fair enough, maybe this is a non-issue. Thanks for your time!
